version: '3'
services:
<<<<<<< HEAD
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27107

  mongo-seed:
    build: mongo_data
    depends_on:
      - mongo

  redis:
    image: redis
    build: redis_data
    container_name: redis
    ports:
      - 6379:6379

  backend:
    image: springboot
    container_name: backend
    build: backend
    ports:
      - 8081:8081
    links:
      - mongo
      - redis

  frontend:
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
=======
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./web:/app/web
    environment:
      - DEBUG=1
  db:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_user_pw
>>>>>>> parent of 75b2ea1 (Docker configurations)
