version: '3.8'
services:
  mongo:
    build: mongo_data
    container_name: mongo
    ports:
      - 27017:27107

  redis:
    image: redis
    build: redis_data
    hostname: redis
    container_name: redis
    # restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  backend:
    image: springboot
    container_name: backend
    build: backend
    ports:
      - 8081:8081
    links:
      - mongo
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  frontend:
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    