version: '3.8'
services:

  mongo:
    image: mongo
    container_name: mongo
    build: mongo_data
    ports:
      - 27017:27107

  redis:
    image: redis
    build: redis_data
    container_name: redis
    ports:
      - 6379:6379

  backend:
    image: springboot
    container_name: backend
    build: backend
    ports:
      - 8081:8081
    links:
      - mongo
      - redis

  frontend:
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend