FROM mongo

# RUN mongoimport --db biddingDB --collection User --type json --file /data/collections/User.json
# RUN mongoimport --db biddingDB --collection Product --type json --file /data/collections/Product.json
# RUN mongoimport --db biddingDB --collection Auction --type json --file /data/collections/Auction.json

CMD [ "mongod" ]

